# Generated by Django 4.0.4 on 2022-05-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vacation',
            fields=[
                ('empID', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('empName', models.CharField(max_length=30)),
                ('vacdate', models.DateField(null=True)),
                ('vacreason', models.CharField(max_length=500)),
            ],
        ),
    ]
