# Generated by Django 4.0.4 on 2022-05-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accvacation',
            fields=[
                ('empID', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('empName', models.CharField(max_length=30)),
                ('vacdate', models.DateField(null=True)),
                ('vacreason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('empID', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('empName', models.CharField(max_length=30)),
                ('bdate', models.DateField(null=True)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=300)),
                ('salary', models.IntegerField(null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('Mstate', models.IntegerField(choices=[(0, 'single'), (1, 'Married')])),
            ],
        ),
        migrations.CreateModel(
            name='subvacation',
            fields=[
                ('empID', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('empName', models.CharField(max_length=30)),
                ('vacdate', models.DateField(null=True)),
                ('vacreason', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='vacation',
        ),
    ]
