# Generated by Django 4.0.4 on 2022-05-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_accvacation_employees_subvacation_delete_vacation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subvacation',
            new_name='vacation',
        ),
        migrations.DeleteModel(
            name='accvacation',
        ),
    ]
