# Generated by Django 4.0.4 on 2022-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_subvacation_vacation_delete_accvacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='approvedvacation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='availablevacation',
            field=models.IntegerField(null=True),
        ),
    ]
