# Generated by Django 4.0.4 on 2022-05-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_employees_approvedvacation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='accvacation',
            fields=[
                ('empID', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('empName', models.CharField(max_length=30)),
                ('vacdate', models.DateField(null=True)),
                ('vacreason', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='vacation',
            new_name='subvacation',
        ),
    ]
