# Generated by Django 4.0.4 on 2022-05-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_accvacation_rename_vacation_subvacation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subvacation',
            new_name='vacation',
        ),
    ]
