# Generated by Django 4.0.4 on 2022-05-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_subvacation_vacation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='vacdate',
            new_name='vacfdate',
        ),
        migrations.AddField(
            model_name='vacation',
            name='vactdate',
            field=models.DateField(null=True),
        ),
    ]
