# Generated by Django 4.0.4 on 2022-05-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_rename_vacdate_vacation_vacfdate_vacation_vactdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accvacation',
            old_name='vacdate',
            new_name='vacfdate',
        ),
        migrations.AddField(
            model_name='accvacation',
            name='vactdate',
            field=models.DateField(null=True),
        ),
    ]
